Add modified files
faemmi/vissl pull request #1
Opened 2023-06-07 14:33 UTC by faemmi

2023-08-01 12:53 UTC, kristian4cast requested changes

2023-08-01 12:53 UTC, kristian4cast commented on Makefile
> +        config.CHECKPOINT.DIR=${OUTPUT_DIR} \
any reason why using {} instead of () here?
wuerde man nicht allgemein {} bevorzugen oder muss man () hier nutzen?

2023-08-01 12:53 UTC, kristian4cast commented on mlflow/deepclusterv2/run.sbatch
> +fi
das kommt von vissl oder?

2023-08-02 14:57 UTC, fabian4cast commented on mlflow/deepclusterv2/run.sbatch
> +fi
Das kommt von der Config für DeepClusterV2.

2023-08-02 14:58 UTC, fabian4cast commented on Makefile
> +        config.CHECKPOINT.DIR=${OUTPUT_DIR} \
`()` refers to make variables, i.e. variables defined in the makefile, whereas `{}` refers to environment variables.

2023-08-03 15:02 UTC, fabian4cast commented
I don't want to merge into main since I fear a lot is going to break. I will close this PR and merge following PRs into `v0.1.6-modified` branch

2023-08-03 15:02 UTC, closed without merging